<?php

namespace App\Console\Commands;

use App\Traits\SanctionMethods;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Log;

class GetPdfsCron extends Command
{
    use SanctionMethods;
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'getpdfs:cron';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Run this command for getting all pdfs that are generated by https://api.sanctionssearch.com/';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
        Log::info("GetPdfsCron is working fine inside App/Console/Commands/GetPdfsCron.php!");

        //Running curl job for getting all pdfs from sanction api
        //Trait method
//        self::GetPdfs();
    }
}
